# fly.toml app configuration file generated for backenddep12314 on 2023-07-20T17:15:19+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backenddep12314"
primary_region = "otp"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
